language: generic 

sudo: required
services: 
- docker

before_install: 
  - docker build -t charlytron/docker-react-2021 -f Dockerfile.dev .

script:
  - docker run -e CI=true charlytron/docker-react-2021 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-725071271937"
  bucket_path: "docker"
  on: 
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY